name: Rock Build

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact
        required: true
        type: string
      path:
        description: Path to the rockcraft.yaml file
        required: true
        type: string

jobs:
  build-rock:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: canonical/craft-actions/rockcraft-pack@91513c1bae43bc871c85ea2fdf2ac7eed91034f9 # main
        id: rockcraft
        with:
          rockcraft-channel: edge
          path: ${{ inputs.path }}

      - name: Save container image to file
        run: |
          mv ${{ inputs.path }}/*.rock .
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo --insecure-policy copy oci-archive:"${rock_file}" docker-daemon:${{ inputs.artifact-name }}:latest
          docker save -o ${{ inputs.artifact-name }}-${{ matrix.arch }}.tar ${{ inputs.artifact-name }}:latest

      - name: Upload container image to GitHub Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}-${{ matrix.arch }}
          path: ${{ inputs.artifact-name }}-${{ matrix.arch }}.tar
