name: Publish Rock

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact
        required: true
        type: string
      path:
        description: Path to the rockcraft.yaml file
        required: true
        type: string

jobs:
  publish-image:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}-${{ matrix.arch }}

      - name: Import and push to github package (${{ matrix.arch }})
        run: |
          version="$(yq '.version' ${{ inputs.path }}/rockcraft.yaml)"
          docker load -i ${{ inputs.artifact-name }}-${{ matrix.arch }}.tar
          docker tag ${{ inputs.artifact-name }}:latest ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}-${{ matrix.arch }}
          docker push ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}-${{ matrix.arch }}

  make-manifest:
    needs: publish-image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          version="$(yq '.version' ${{ inputs.path }}/rockcraft.yaml)"

          docker manifest create ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version} \
            ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}-amd64 \
            ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}-arm64

          docker manifest create ghcr.io/ellanetworks/${{ inputs.artifact-name }}:latest \
            ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}-amd64 \
            ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}-arm64

          docker manifest push ghcr.io/ellanetworks/${{ inputs.artifact-name }}:${version}
          docker manifest push ghcr.io/ellanetworks/${{ inputs.artifact-name }}:latest
